In [13]:
import pandas as pd

df = pd.read_csv("../data/Social_Network_Ads.csv")

df.sample(5)

User ID  Gender  Age  EstimatedSalary  Purchased
376  15596984  Female   46            74000          0
75   15651983    Male   34           112000          1
65   15718071    Male   24            58000          0
388  15672330    Male   47            34000          1
363  15768293  Female   42            79000          0

In [14]:
print(df.dtypes)

User ID            int64
Gender               str
Age                int64
EstimatedSalary    int64
Purchased          int64
dtype: object


In [15]:
df['Age'] = df['Age'].astype('category')
df['Gender'] = df['Gender'].astype('category')

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X = df[['EstimatedSalary','Age']]
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.3, random_state = 42
)

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [17]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

print(y_train.values[:5],y_train_pred[:5])
print(y_test.values[:5],y_test_pred[:5])


[0 0 1 1 1] [0 0 0 1 0]
[0 1 0 1 0] [0 1 0 1 0]


In [ ]:
from sklearn.metrics import confusion_matrix
print("confusion matrix on y_train and y_train_pred")
print(confusion_matrix(y_train, y_train_pred))
print("confusion matrix on y_test and y_text_pred")
print(confusion_matrix(y_test, y_test_pred))

confusion matrix on y_train and y_train_pred
[[169  15]
 [ 32  64]]
confusion matrix on y_test and y_text_pred
[[71  2]
 [16 31]]


In [20]:
from sklearn.metrics import classification_report
print("metrics on y_train and y_train_pred")
print(classification_report(y_train, y_train_pred))
print("metrics on y_test and y_test_pred")
print(classification_report(y_test, y_test_pred))

metrics on y_train and y_train_pred
              precision    recall  f1-score   support

           0       0.84      0.92      0.88       184
           1       0.81      0.67      0.73        96

    accuracy                           0.83       280
   macro avg       0.83      0.79      0.80       280
weighted avg       0.83      0.83      0.83       280

metrics on y_test and y_test_pred
              precision    recall  f1-score   support

           0       0.82      0.97      0.89        73
           1       0.94      0.66      0.78        47

    accuracy                           0.85       120
   macro avg       0.88      0.82      0.83       120
weighted avg       0.86      0.85      0.84       120



In [22]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error
from sklearn.compose import TransformedTargetRegressor
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import pandas as pd

df = pd.read_csv("../data/Social_Network_Ads.csv")

X = df[['EstimatedSalary','Gender', 'Age']]
y = df['Purchased']
categorical_cols = ['Gender', 'Age']
numerical_cols = ['EstimatedSalary']

#--- PROCESS 1: None Normalized ---
# Only transforms categories to numbers; keeps numerical values as they are.
preprocessor_simple = ColumnTransformer(
    transformers=[
    ('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), categorical_cols)
    ],
    remainder='passthrough' # Keeps numerical columns unchanged
)
model_none_normalized = Pipeline(steps=[
    ('preprocessor', preprocessor_simple),
    ('lr', LogisticRegression())
])

# --- PROCESS 2: Normalized Process ---
# Transforms categories AND scales numerical features to a similar range (Mean=0, Std=1).
preprocessor_scaled = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), categorical_cols ),
        ('num', StandardScaler(), numerical_cols)
    ]
)
model_normalized = Pipeline(steps=[
    ('preprocessor', preprocessor_scaled),
    ('lr', LogisticRegression())
])
    
# For Target Normalization
model_with_norm = TransformedTargetRegressor(
    regressor=model_normalized,
    transformer=StandardScaler() 
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.3, random_state = 42
)

model_none_normalized.fit(X_train, y_train)
model_normalized.fit(X_train, y_train)


/Users/hinadome/code/bootcamp_macaw_04_26/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['Gender', 'Age']),
                                                 ('num', StandardScaler(),
                                                  ['EstimatedSalary'])])),
                ('lr', LogisticRegression())])

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_train_pred_none_normalized = model_none_normalized.predict(X_train)
y_test_pred_none_normalized = model_none_normalized.predict(X_test)

y_train_pred_normalized = model_normalized.predict(X_train)
y_test_pred_normalized = model_normalized.predict(X_test)

print("====none-normalized====")
print("confusion matrix on y_train and y_train_pred")
print(confusion_matrix(y_train, y_train_pred_none_normalized))
print("confusion matrix on y_train and y_train_pred")
print(confusion_matrix(y_test, y_test_pred_none_normalized))
print("metrics on y_train and y_train_pred")
print(classification_report(y_train, y_train_pred_none_normalized))
print("metrics on y_test and y_test_pred")
print(classification_report(y_test, y_test_pred_none_normalized))
print("====normalized====")
print("confusion matrix on y_train and y_train_pred")
print(confusion_matrix(y_train, y_train_pred_normalized))
print("confusion matrix on y_train and y_train_pred")
print(confusion_matrix(y_test, y_test_pred_normalized))
print("metrics on y_train and y_train_pred")
print(classification_report(y_train, y_train_pred_normalized))
print("metrics on y_test and y_test_pred")
print(classification_report(y_test, y_test_pred_normalized))

====none-normalized====
confusion matrix on y_train and y_train_pred
[[173  11]
 [ 38  58]]
confusion matrix on y_train and y_train_pred
[[72  1]
 [24 23]]
metrics on y_train and y_train_pred
              precision    recall  f1-score   support

           0       0.82      0.94      0.88       184
           1       0.84      0.60      0.70        96

    accuracy                           0.82       280
   macro avg       0.83      0.77      0.79       280
weighted avg       0.83      0.82      0.82       280

metrics on y_test and y_test_pred
              precision    recall  f1-score   support

           0       0.75      0.99      0.85        73
           1       0.96      0.49      0.65        47

    accuracy                           0.79       120
   macro avg       0.85      0.74      0.75       120
weighted avg       0.83      0.79      0.77       120

====normalized====
confusion matrix on y_train and y_train_pred
[[173  11]
 [ 31  65]]
confusion matrix on y_train and y

/Users/hinadome/code/bootcamp_macaw_04_26/.venv/lib/python3.13/site-packages/sklearn/preprocessing/_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
/Users/hinadome/code/bootcamp_macaw_04_26/.venv/lib/python3.13/site-packages/sklearn/preprocessing/_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)


1. true positive (TP): model correctly predicts positive class
2. true negative (TN): model correctly predicts negative class
3. false positive (FP): model incorrectly predicts positive class (type I error)
4. false negative (FN): model incorrectly predicts negative class (type II error)

# Precision and Recall
- Precision: measures the accuracy of positive predictions
- Recall: measures ability to identify all relevant positive instances

In [24]:
tp = y_train[(y_train == 1) & (y_train_pred == 1)].count()
tn = y_train[(y_train == 0) & (y_train_pred == 0)].count()
fp = y_train[(y_train == 0) & (y_train_pred == 1)].count()
fn = y_train[(y_train == 1) & (y_train_pred == 0)].count()

print(f"True Positives: {tp}")
print(f"True Negatives: {tn}")
print(f"False Positives: {fp}")
print(f"False Negatives: {fn}")

True Positives: 64
True Negatives: 169
False Positives: 15
False Negatives: 32


In [25]:
example_pred = [0, 1, 1, 0, 1, 0, 1, 0, 0, 1]
example_true = [0, 1, 0, 0, 1, 0, 1, 1, 1, 1]

In [ ]:
# 1 side of Precision
pred_1 = 5
pred_1_matching_true_1 = 4
precision = 4 / 5
print(precision)

0.8


In [ ]:
# 1 side of Recall
pred_1_matching_true_1 = 4
true_1 = 6
recall = 4 / 6
print(recall) 

0.6666666666666666


In [34]:
# 0 side of Precision
pred_0 = 5
pred_0_matching_true_0 = 3
precision = 3 / 5
print(precision)

0.6


In [35]:
# 0 side of Recall
pred_0_matching_true_0 = 3
true_0 = 4
recall = 3 / 4
print(recall)

0.75


In [33]:
from sklearn.metrics import classification_report
print(classification_report(example_true, example_pred))

              precision    recall  f1-score   support

           0       0.60      0.75      0.67         4
           1       0.80      0.67      0.73         6

    accuracy                           0.70        10
   macro avg       0.70      0.71      0.70        10
weighted avg       0.72      0.70      0.70        10

